### ISSUE TITLE
Improve exception handling when connection terminates

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#101]
Currently, when the network connection between exporter and HMC is terminated (after it was running for a while), the exporter shows a long series of re-raised exceptions ("during handling of the above exception, another exception occurred"). The last few re-raisings in this sequence are shown below.

The goal is to make the handling of this situation more user-friendly, e.g. to display an error message and retry indefinitely. Note that retries at the level of the "requests" package have already been exhausted at this point, so there is not really a value in adding another retry loop with a limited retry count around that. Reasonable behaviors would be (1) to terminate and (2) to retry indefinitely. For a exporter running in an unobserved manner, retrying indefinitely is probably the most reasonable behavior. That's what the Prometheus and Grafana servers also do when they cannot get data from their sources (although the situation is different there since it is only one of multiple data sources).

Note that similar issues exist when there is no network connection in the first place, but the exceptions raised are slightly different. Nevertheless, if we go for indefinite retries when a working connection is terminated, that behavior should probably also be implemented when establishing the connection initially.

The current code terminates when it cannot establish an initial connection, but retries when an existing connection is broken, resuming properly after the connection has been re-established.

The example below is from when an existing network connection is terminated after some time.

```
. . .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_session.py", line 764, in get
    result = req.get(url, headers=self.headers, verify=False,
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.16.192.15', port=6794): Max retries exceeded with url: /api/services/metrics/context/1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='172.16.192.15', port=6794): Read timed out. (read timeout=3600)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/Projects/zhmcclient/repos/zhmc-prometheus-exporter/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 87, in zhmc_exceptions
    yield
  File "/Users/maiera/Projects/zhmcclient/repos/zhmc-prometheus-exporter/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 572, in collect
    metrics_object = retrieve_metrics(self.context)
  File "/Users/maiera/Projects/zhmcclient/repos/zhmc-prometheus-exporter/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 411, in retrieve_metrics
    retrieved_metrics = context.get_metrics()
  File "<decorator-gen-165>", line 2, in get_metrics
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_logging.py", line 223, in log_api_call
    result = func(*args, **kwargs)
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_metrics.py", line 332, in get_metrics
    metrics_response = self.manager.session.get(self.uri)
  File "<decorator-gen-18>", line 2, in get
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_logging.py", line 223, in log_api_call
    result = func(*args, **kwargs)
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_session.py", line 767, in get
    _handle_request_exc(exc, self.retry_timeout_config)
  File "/Users/maiera/Projects/zhmcclient/repos/python-zhmcclient/zhmcclient/_session.py", line 77, in _handle_request_exc
    raise ConnectionError(_request_exc_message(exc), exc)
zhmcclient._exceptions.ConnectionError: HTTPSConnectionPool(host='172.16.192.15', port=6794): Read timed out. (read timeout=3600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/Users/maiera/virtualenvs/zhmc38/lib/python3.8/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/Users/maiera/Projects/zhmcclient/repos/zhmc-prometheus-exporter/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 589, in collect
    family_objects = build_family_objects(metrics_object,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/maiera/Projects/zhmcclient/repos/zhmc-prometheus-exporter/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 89, in zhmc_exceptions
    raise ConnectionError("Connection error using IP address {} defined "
zhmc_prometheus_exporter.zhmc_prometheus_exporter.ConnectionError: Connection error using IP address 172.16.192.15 defined in HMC credentials file myconfig/hmccreds_az3.yaml: HTTPSConnectionPool(host='172.16.192.15', port=6794): Read timed out. (read timeout=3600)
```

**Comment by andy-maier** [comment]
**DISCUSSION:**
* Should we go for indefinitely retrying on lost connections?
* if so, does it need to be selectable e.g. by an option?

**Comment by andy-maier** [comment]
PR #141 addresses this by leaving no tracebacks anymore and transforming all errors into proper error messages, and by having an eternal retry loop around the main collection loop, to recover any connectivity losses.
