### ISSUE TITLE
Exporters enter error state after HMC restart

### ISSUE THREAD

**Issue by dwhayslett** [zhmcclient/zhmc-prometheus-exporter#193]
After one of our HMCs are restarted (for application of MCLs, for example), our exporters enter an error state and display "server returned HTTP status 500 Interal Server Error" in our <prometheus>/targets page.

In /var/log/messages, there's this:

Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]: Traceback (most recent call last):
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/lib64/python3.9/wsgiref/handlers.py", line 137, in run
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    self.result = application(self.environ, self.start_response)
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 122, in prometheus_app
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    status, header, output = _bake_output(registry, accept_header, params)
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    output = encoder(registry)
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 22, in generate_latest
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    for metric in registry.collect():
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 83, in collect
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    for metric in collector.collect():
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 978, in collect
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    break
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    self.gen.throw(type, value, traceback)
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:  File "/usr/local/lib/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 137, in zhmc_exceptions
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]:    raise new_exc  # AuthError
Feb 13 00:01:10 kq9la8t zhmc_prometheus_exporter[3930487]: zhmc_prometheus_exporter.zhmc_prometheus_exporter.AuthError: Authentication error when logging on to the HMC at 172.29.120.38 using userid 'metrics-operator' defined in HMC credentials file dal-z15-hmccreds.yaml: HTTP authentication failed: No session id was provided (must login)

Seems like the exporter isn't recognizing that it needs to log back into the HMC, perhaps?  What other information would be helpful for this?

**Comment by andy-maier** [comment]
First, sorry for the delay.

The zhmcclient generally performs a re-login in case an operation results in HTTP 403.5 (session id expired).

What is not clear is which operation in your specific case got the auth error back from the HMC, the original GET for pulling metrics, or the re-logon. Also, the reason code from that auth error is not shown unfortunately.

If you can reproduce the error with logging turned on in the exporter (`--log file.log --log-comp hmc`) and post the part of the log where it fails, that would be great. Otherwise I try to investigate this on my end.

**Comment by andy-maier** [comment]
I did some fixes and improvements in this area, and verified that the exporter is now able to properly survive an HMC reboot. These changes are in PR #196, which will be included in version 1.1.0.

However, I was not able to reproduce your exact error when I rebooted the HMC. I had a different error, which I fixed in the PR. So there is a chance that I did not fix your error. In any case, the changes will ensure that there is now information about the HMC operation and its status and reason code when it fails again, so that it can be more easily debugged then.

You may want to enable logging for some time (`--log file.log --log-comp hmc --log-comp exporter`). Note that this  grows the log file regularly, every time Prometheus pulls metrics.

If you have a chance to install from the branch of that PR (or from the master branch once the PR is merged) and reproduce the error, that would be great. If not, then we'll just release the new version in a while and we'll see.

**Comment by andy-maier** [comment]
We closed this issue after merging the PR. If the error reoccurs with this change, please feel free to either reopen this issue, or to create a new one.
