### ISSUE TITLE
Error happens during starting

### ISSUE THREAD

**Issue by amber-zhang** [zhmcclient/zhmc-prometheus-exporter#20]
Running zhmcexporter as docker container in Z system. Following error happens when starting the container. But looks like the error is endured. When invoking curl to access zhmcexporter, metrics info can be got.

[init(1) v20180222] running /.runq/SIGUSR1 PID=120

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Thu Oct 25 07:26:43 UTC 2018
!!! MAINTENANCE SESSION START !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[init(1) v20180222] pid 120: exit status: 0
[init(1) v20180222] running /.runq/SIGUSR2 PID=140

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Thu Oct 25 07:27:20 UTC 2018
!!! MAINTENANCE SESSION ENDED !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[init(1) v20180222] pid 140: exit status: 0
[init(1) v20180222] running /.runq/SIGUSR1 PID=148

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Fri Oct 26 02:35:38 UTC 2018
!!! MAINTENANCE SESSION START !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[init(1) v20180222] pid 148: exit status: 0
[init(1) v20180222] running /.runq/SIGUSR2 PID=170

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Fri Oct 26 02:36:23 UTC 2018
!!! MAINTENANCE SESSION ENDED !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[init(1) v20180222] pid 170: exit status: 0
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 47592)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 145, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 88, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/core.py", line 147, in collect
    for metric in collector.collect():
  File "/usr/local/zhmc_prometheus_exporter.py", line 351, in collect
    retrieved_metrics = retrieve_metrics(self.context)
  File "/usr/local/zhmc_prometheus_exporter.py", line 242, in retrieve_metrics
    retrieved_metrics = context.get_metrics()
  File "<decorator-gen-125>", line 2, in get_metrics
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_metrics.py", line 334, in get_metrics
    metrics_response = self.manager.session.get(self.uri)
  File "<decorator-gen-18>", line 2, in get
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_session.py", line 729, in get
    return self.get(uri, logon_required)
  File "<decorator-gen-18>", line 2, in get
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_session.py", line 736, in get
    raise HTTPError(result_object)
zhmcclient._exceptions.HTTPError: 404,1: Context specified is not found. [GET /api/services/metrics/context/1]
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 47596)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 145, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 88, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/core.py", line 147, in collect
    for metric in collector.collect():
  File "/usr/local/zhmc_prometheus_exporter.py", line 351, in collect
    retrieved_metrics = retrieve_metrics(self.context)
  File "/usr/local/zhmc_prometheus_exporter.py", line 242, in retrieve_metrics
    retrieved_metrics = context.get_metrics()
  File "<decorator-gen-125>", line 2, in get_metrics
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_metrics.py", line 334, in get_metrics
    metrics_response = self.manager.session.get(self.uri)
  File "<decorator-gen-18>", line 2, in get
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zhmcclient/_session.py", line 736, in get
    raise HTTPError(result_object)
zhmcclient._exceptions.HTTPError: 404,1: Context specified is not found. [GET /api/services/metrics/context/1]
----------------------------------------
[proxy v20180222] forwarding signal '15' to init

**Comment by amber-zhang** [comment]
The problem could arise from session/context change because of prometheus server restart

**Comment by andy-maier** [comment]
@amber-zhang Hi Amber. Does the problem still occur?

**Comment by andy-maier** [comment]
Not clear whether this still exists. Please open a new issue in case this re-occurs.
