### ISSUE TITLE
Extremely verbose exception output when host doesn't exist

### ISSUE THREAD

**Issue by sterlingbates** [zhmcclient/zhmc-prometheus-exporter#30]
This may be in the zhmcclient, but just in case it isn't I'll put it here.

**Steps to Reproduce**
1. Point the exporter to an IP that doesn't exist.
2. Watch as the logs fill up with multiple layers of `During handling of the above exception, another exception occurred` dumps.

**Expected Behavior**
If the host is unavailable then a single `No route to host` line (maybe a small stack) should be sufficient.

**Existing Behavior**
It's very likely that the output below is two separate stacks commingled, but that's an artifact of how logs are shipped. We get this and sometimes more.

```
 zhmcclient._exceptions.ConnectionError: Failed to establish a new connection: [Errno 113] No route to host 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection 
     conn = self._new_conn() 
     conn.connect() 
 OSError: [Errno 113] No route to host 
     self, "Failed to establish a new connection: %s" % e) 
     self._validate_conn(conn) 
     (self._dns_host, self.port), self.timeout, **extra_kw) 
 Traceback (most recent call last): 
  
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 169, in _new_conn 
     sock.connect(sa) 
  
 During handling of the above exception, another exception occurred: 
 During handling of the above exception, another exception occurred: 
 urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x3ff955d02e8>: Failed to establish a new connection: [Errno 113] No route to host 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 344, in _make_request 
     chunked=chunked) 
     raise err 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 160, in _new_conn 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 316, in connect 
  
 Traceback (most recent call last): 
   File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send 
     timeout=timeout 
     **response_kw) 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 641, in urlopen 
     **response_kw) 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen 
     _stacktrace=sys.exc_info()[2]) 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 399, in increment 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen 
     **response_kw) 
  
 During handling of the above exception, another exception occurred: 
   raise MaxRetryError(_pool, url, error or ResponseError(cause)) 
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='x.x.x.x', port=6794): Max retries exceeded with url: /api/sessions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x3ff955d02e8>: Failed to establish a new connection: [Errno 113] No route to host',)) 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 843, in _validate_conn 
  
 Traceback (most recent call last): 
   File "/usr/local/lib/python3.6/dist-packages/zhmcclient/_session.py", line 949, in post 
   File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 670, in urlopen 
     verify=False, timeout=req_timeout) 
   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 581, in post 
     return self.request('POST', url, data=data, json=json, **kwargs) 
     resp = self.send(prep, **send_kwargs) 
   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request 
     r = adapter.send(request, **kwargs)
```

**Comment by andy-maier** [comment]
Hi Sterling. Sorry for not reacting earlier.

It turned out that the exporter did not handle all possible exceptions raised by the zhmcclient library. Exceptions not handled resulted in printing the traceback, which in cases where a particular exception is re-raised as another one, displays the confusing "Another exception occurred ..." message that makes it hard to understand what is really going on.

PR #41 (targeted for 0.4.1) addresses the exception handling. I consider this issue closed. If you still encounter problems with the exporter, please open a new issue.
