### ISSUE TITLE
Address wrong socket type error

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-prometheus-exporter#71]
Every now and then, presumably when Prometheus contacts the exporter using https or when a browser directed to the export port uses https, the exporter thread that serves the export port, shows an OSError complaining about the wrong socket type.

**Comment by andy-maier** [comment]
Example when calling with `-vv`:
```
Collecting metrics
Fetching metrics from HMC
Building family objects
Returning family objects
Done collecting metrics
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 288, in write
    self.send_headers()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 346, in send_headers
    self.send_preamble()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 272, in send_preamble
    self._write(('Server: %s\r\n' % self.server_software).encode('iso-8859-1'))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
Collecting metrics
Fetching metrics from HMC
Building family objects
Returning family objects
Done collecting metrics

```
